Repository jamstack/jamstack.org, pull requests merged in 2021-08, with the labels that each got.

#630 A concise glossary entry for Jamstack itself
  src/site/_data/glossary.yaml
Labels: content

#607 Adds GitHub action to do daily build
  .github/workflows/scheduled-build.yml
Labels: enhancement

#489 Added goonlinetools.com
  src/site/_data/examples/goonlinetools.yaml
  src/site/img/examples/goonlinetools.png
Labels: blocked
