Repository jamstack/jamstack.org, pull requests merged in 2022-11, with the labels that each got.

#830 Add y-overflow to sticky nav on short viewports
  src/css/tailwind.css
Labels: enhancement

#831 Move up Jamstack Conf promo section
  src/site/index.njk
Labels: content

#833 Community survey 2022 results
  .eleventy.js
  netlify.toml
  package.json
  src/css/d3chart.css
  src/css/tailwind.css
  src/site/_data/announcementbar.json
  src/site/_includes/banner.njk
  src/site/_includes/components/permalink-heading.njk
  src/site/_includes/header.njk
  src/site/_includes/survey/2021/adoption.njk
  src/site/_includes/survey/2021/choices.njk
  src/site/_includes/survey/2021/conclusion.njk
  src/site/_includes/survey/2021/demographics.njk
  src/site/_includes/survey/2021/experience.njk
  src/site/_includes/survey/2021/workflows.njk
  src/site/_includes/survey/2022/how-are-we-building/cms-usage-vs-satisfaction.njk
  src/site/_includes/survey/2022/how-are-we-building/frameworks-usage-vs-satisfaction-changes.njk
  src/site/_includes/survey/2022/how-are-we-building/frameworks-usage-vs-satisfaction.njk
  src/site/_includes/survey/2022/how-are-we-building/index.njk
  src/site/_includes/survey/2022/how-are-we-building/programming-language-usage-vs-satisfaction.njk
  src/site/_includes/survey/2022/how-are-we-building/smaller-frameworks-usage-vs-satisfaction.njk
  src/site/_includes/survey/2022/what-are-we-building/audience-sizes.njk
  src/site/_includes/survey/2022/what-are-we-building/index.njk
  src/site/_includes/survey/2022/what-are-we-building/target-devices-by-type.njk
  src/site/_includes/survey/2022/what-are-we-building/types-of-sites-built-last-12-months.njk
  src/site/_includes/survey/2022/what-are-we-building/what-is-the-purpose-of-the-sites-you-built-in-2022.njk
  src/site/_includes/survey/2022/where-are-we-going/index.njk
  src/site/_includes/survey/2022/where-are-we-going/serverless.njk
  src/site/_includes/survey/2022/where-are-we-going/web-components.njk
  src/site/_includes/survey/2022/where-are-we-going/web3-feelings.njk
  src/site/_includes/survey/2022/where-are-we-going/web3-usage.njk
  src/site/_includes/survey/2022/whos-doing-the-building/employment-status.njk
  src/site/_includes/survey/2022/whos-doing-the-building/experience-by-region.njk
  src/site/_includes/survey/2022/whos-doing-the-building/experience-increasing-over-time.njk
  src/site/_includes/survey/2022/whos-doing-the-building/have-you-changed-jobs-in-the-last-12-months.njk
  src/site/_includes/survey/2022/whos-doing-the-building/i-changed-jobs-to-work-remotely-more-often.njk
  src/site/_includes/survey/2022/whos-doing-the-building/i-enjoy-remote-work.njk
  src/site/_includes/survey/2022/whos-doing-the-building/i-would-like-to-work-remote-more-often.njk
  src/site/_includes/survey/2022/whos-doing-the-building/i-would-quit-my-job-if-in-person-was-more-often.njk
  src/site/_includes/survey/2022/whos-doing-the-building/i-would-quit-my-job-if-remote-was-more-often.njk
  src/site/_includes/survey/2022/whos-doing-the-building/index.njk
  src/site/_includes/survey/2022/whos-doing-the-building/job-title-2021-vs-2022.njk
  src/site/_includes/survey/2022/whos-doing-the-building/my-company-has-remote-work-figured-out.njk
  src/site/_includes/survey/2022/whos-doing-the-building/remote-changes.njk
  src/site/_includes/survey/2022/whos-doing-the-building/remote-frequency.njk
  src/site/_includes/survey/2022/whos-doing-the-building/respondents-by-region.njk
  src/site/_includes/survey/2022/whos-doing-the-building/what-influenced-leaving.njk
  src/site/_includes/survey/2022/whos-doing-the-building/what-influenced-staying.njk
  src/site/img/og/jamstack-community-survey-2022-og.png
  src/site/survey/2021.njk
  src/site/survey/2021/d3chart-survey-2021.js
  src/site/survey/2021/d3chart.js
  src/site/survey/2021/js.njk
  src/site/survey/2022.njk
  src/site/survey/2022/community-survey-2022-methodology.pdf
  src/site/survey/2022/d3chart-survey-2022.js
  src/site/survey/2022/js.njk
  src/site/survey/shared/d3chart.js
Labels: enhancement

#834 Add link to 2021 results
  src/site/_includes/survey/2022/where-are-we-going/index.njk
Labels: chore

#832 Refactor logos ticker and fix overflow
  src/site/_includes/components/ticker.njk
  src/site/_includes/layouts/base.njk
  src/site/css/ticker.css
Labels: bug
